In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/MMLA Datasets/FinMark CSV/customer_demographics_contaminated.csv")

In [ ]:
print("No. of records:", df.shape[0])
print("No. of columns:", df.shape[1])

No. of records: 3200
No. of columns: 6

In [ ]:
df.describe()

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
count,3200,2909,3200,3200,2897,3200
unique,3000,58,2,2696,3,1544
top,2bdd585a-301b-4935-a32d-295b34e81010,57.0,Female,Port Michael,High,2024-06-08
freq,2,72,1610,6,1004,9

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3200 entries, 0 to 3199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   3200 non-null   object
 1   Age          2909 non-null   object
 2   Gender       3200 non-null   object
 3   Location     3200 non-null   object
 4   IncomeLevel  2897 non-null   object
 5   SignupDate   3200 non-null   object
dtypes: object(6)
memory usage: 150.1+ KB

In [ ]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 177

In [ ]:
duplicates = df[df.duplicated(keep=False)]
display(duplicates)

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
9,40f5a5dd-a46f-4a5e-8c0f-fe04389ddec8,NaN,Female,Mariaberg,High,2024-02-18
18,8de7560f-370d-4cfd-8135-20a3de237264,31.0,Female,Colemanstad,Low,2020-12-01
23,fd63f236-3ec3-401d-9fa1-53bda0bd7c0e,NaN,Male,Thomasbury,Low,2021-05-29
54,c9f831b4-43cf-4ed9-9b47-09542e239c70,53.0,Female,East Ryanbury,Medium,2023-10-12
56,348c5ab5-992d-4780-ba71-d1a5e3818191,46.0,Female,New Jesseside,Low,2023-09-24
...,...,...,...,...,...,...
3194,40c2909d-983b-4c95-a737-2022acba98ee,28.0,Male,Josephborough,High,2020-02-14
3196,0ef84cc6-0b4c-4c56-bdaa-d6b725ccc08e,40.0,Male,Lisaside,Medium,2022-07-23
3197,0ede97d1-bb46-452d-893e-b63f37da4fa8,NaN,Female,North Christinaport,High,2021-10-16
3198,43ec68f5-4305-4b40-8ced-a187d00bb3f5,26.0,Female,Carrilloport,Low,2022-09-26
3199,077936e6-6556-434f-9494-e5d671b6e71c,65.0,Female,Bryantside,High,2019-11-09

In [ ]:
duplicates = df[df.duplicated(keep=False)].sort_values(
    by=["CustomerID", "Location"]
)

display(duplicates)

,CustomerID,Age,Gender,Location,IncomeLevel,SignupDate
2559,0047d8ce-a5bb-4db7-860f-6ff66e1cd060,40.0,Male,Mitchellview,Medium,2021-11-11
3039,0047d8ce-a5bb-4db7-860f-6ff66e1cd060,40.0,Male,Mitchellview,Medium,2021-11-11
1511,05609335-a647-4691-80a8-82b43518b767,52.0,Male,Jonesside,Low,2023-10-07
3169,05609335-a647-4691-80a8-82b43518b767,52.0,Male,Jonesside,Low,2023-10-07
1105,06af0246-5f53-45f4-997e-bf42706b11d7,53.0,Male,Stevenberg,NaN,2022-11-25
...,...,...,...,...,...,...
3113,fd35b6b4-ad1c-49cc-9c34-8c2d696f38e2,42.0,Male,Karenbury,Low,2024-04-14
23,fd63f236-3ec3-401d-9fa1-53bda0bd7c0e,NaN,Male,Thomasbury,Low,2021-05-29
3148,fd63f236-3ec3-401d-9fa1-53bda0bd7c0e,NaN,Male,Thomasbury,Low,2021-05-29
165,fe3b0536-0a29-4ef4-a8bb-6fbc3171d44f,59.0,Female,East Nathantown,High,2022-04-14
3011,fe3b0536-0a29-4ef4-a8bb-6fbc3171d44f,59.0,Female,East Nathantown,High,2022-04-14

In [ ]:
df = df.drop_duplicates()

In [ ]:
print("Duplicates:", df.duplicated().sum())
print("Records remaining:", len(df))

Duplicates: 0
Records remaining: 3023

In [ ]:
missing_values = df.isnull().sum()

print(missing_values)

CustomerID       0
Age            276
Gender           0
Location         0
IncomeLevel    285
SignupDate       0
dtype: int64

In [ ]:
print("Age data type:", df["Age"].dtype)

Age data type: object

In [ ]:
print(df["Age"].value_counts().head(30))

Age
62.0    70
57.0    67
34.0    64
26.0    64
68.0    62
55.0    58
70.0    56
43.0    56
61.0    56
25.0    55
36.0    55
18.0    55
52.0    54
45.0    54
37.0    54
59.0    54
27.0    54
58.0    53
53.0    53
64.0    52
23.0    52
56.0    51
38.0    51
49.0    50
28.0    50
46.0    50
66.0    50
63.0    49
42.0    49
67.0    49
Name: count, dtype: int64

In [ ]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")

In [ ]:
print("Age data type:", df["Age"].dtype)
print("Missing values:", df["Age"].isna().sum())
print("Minimum Age:", df["Age"].min())
print("Maximum Age:", df["Age"].max())

Age data type: float64
Missing values: 310
Minimum Age: -1.0
Maximum Age: 150.0

In [ ]:
print(df["Age"].value_counts().sort_index().head(20))

Age
-1.0     30
 18.0    55
 19.0    48
 20.0    48
 21.0    45
 22.0    38
 23.0    52
 24.0    36
 25.0    55
 26.0    64
 27.0    54
 28.0    50
 29.0    41
 30.0    43
 31.0    46
 32.0    43
 33.0    34
 34.0    64
 35.0    39
 36.0    55
Name: count, dtype: int64

In [ ]:
print(df["Age"].value_counts().sort_index().tail(20))

Age
52.0     54
53.0     53
54.0     43
55.0     58
56.0     51
57.0     67
58.0     53
59.0     54
60.0     47
61.0     56
62.0     70
63.0     49
64.0     52
65.0     47
66.0     50
67.0     49
68.0     62
69.0     48
70.0     56
150.0    33
Name: count, dtype: int64

In [ ]:
print("\nNumber of ages below 0:", (df["Age"] < 0).sum())
print("Number of ages above 100:", (df["Age"] > 100).sum())

Number of ages below 0: 30
Number of ages above 100: 33

In [ ]:
print("Ages below 0:")
print(df.loc[df["Age"] < 0, "Age"].value_counts())

print("\nAges above 100:")
print(df.loc[df["Age"] > 100, "Age"].value_counts())

Ages below 0:
Age
-1.0    30
Name: count, dtype: int64

Ages above 100:
Age
150.0    33
Name: count, dtype: int64

In [ ]:
original_df = pd.read_csv("/content/drive/MyDrive/MMLA Datasets/FinMark CSV/customer_demographics_contaminated.csv")

numeric_age = pd.to_numeric(original_df["Age"], errors="coerce")

print("Non-numeric Age values:")
print(original_df.loc[
    numeric_age.isna() & original_df["Age"].notna(),
    "Age"
].value_counts())

Non-numeric Age values:
Age
Unknown    34
Name: count, dtype: int64

In [ ]:
df.loc[(df["Age"] < 0) | (df["Age"] > 100), "Age"] = pd.NA

In [ ]:
print("Missing/invalid Age values:", df["Age"].isna().sum())
print("Minimum valid Age:", df["Age"].min())
print("Maximum valid Age:", df["Age"].max())

Missing/invalid Age values: 373
Minimum valid Age: 18.0
Maximum valid Age: 70.0

In [ ]:
print("Mean Age:", df["Age"].mean())
print("Median Age:", df["Age"].median())

Mean Age: 44.64490566037736
Median Age: 45.0

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [ ]:
print("Missing Age values:", df["Age"].isna().sum())
print("Age data type:", df["Age"].dtype)
print("Minimum Age:", df["Age"].min())
print("Maximum Age:", df["Age"].max())

Missing Age values: 0
Age data type: float64
Minimum Age: 18.0
Maximum Age: 70.0

In [ ]:
print("IncomeLevel data type:", df["IncomeLevel"].dtype)

print("\nIncomeLevel categories:")
print(df["IncomeLevel"].value_counts(dropna=False))

IncomeLevel data type: object

IncomeLevel categories:
IncomeLevel
High      946
Low       923
Medium    869
NaN       285
Name: count, dtype: int64

In [ ]:
df["IncomeLevel"] = df["IncomeLevel"].fillna("Undetermined")

In [ ]:
print("Missing IncomeLevel values:", df["IncomeLevel"].isna().sum())

print("\nIncomeLevel categories:")
print(df["IncomeLevel"].value_counts())

Missing IncomeLevel values: 0

IncomeLevel categories:
IncomeLevel
High            946
Low             923
Medium          869
Undetermined    285
Name: count, dtype: int64

In [ ]:
print("SignupDate data type:", df["SignupDate"].dtype)

SignupDate data type: object

In [ ]:
print(df["SignupDate"].head(20))

0     2022-11-17
1     2020-07-21
2     2021-01-01
3     2024-06-10
4     2023-08-24
5     2022-02-13
6     2019-12-08
7     2022-04-26
8     2022-04-17
9     2024-02-18
10    2020-09-17
11    2022-08-12
12    2021-12-02
13    2022-04-17
14    2019-08-05
15    2020-01-02
16    2023-10-06
17    2023-07-09
18    2020-12-01
19    2022-01-09
Name: SignupDate, dtype: object

In [ ]:
print(df["SignupDate"].tail(20))

3043    2020-07-30
3051    2024-05-02
3062    2024-04-15
3078    2020-11-06
3079    2022-02-04
3083    12/03/2020
3085    07/11/2019
3087    2023-09-30
3119    18/01/2024
3132    2023-04-04
3138    2024-03-02
3145    2021-02-20
3149    27/05/2021
3150    2020-05-14
3162    2021-09-19
3165    2020-02-26
3178    2020-06-23
3183    2022-07-23
3186    2024-01-10
3195    2023-02-17
Name: SignupDate, dtype: object

In [ ]:
raw_dates = df["SignupDate"].astype("string").str.strip()

parsed_dates = pd.to_datetime(
    raw_dates,
    format="%Y-%m-%d",
    errors="coerce"
)

mask = parsed_dates.isna()

parsed_dates.loc[mask] = pd.to_datetime(
    raw_dates.loc[mask],
    format="%d/%m/%Y",
    errors="coerce"
)

df["SignupDate"] = parsed_dates

In [ ]:
print("SignupDate data type:", df["SignupDate"].dtype)
print("Invalid SignupDate values:", df["SignupDate"].isna().sum())

SignupDate data type: datetime64[ns]
Invalid SignupDate values: 0

In [ ]:
print("FINAL DATASET CHECK")

print("\nShape:")
print(df.shape)

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

FINAL DATASET CHECK

Shape:
(3023, 6)

Data types:
CustomerID             object
Age                   float64
Gender                 object
Location               object
IncomeLevel            object
SignupDate     datetime64[ns]
dtype: object

Missing values:
CustomerID     0
Age            0
Gender         0
Location       0
IncomeLevel    0
SignupDate     0
dtype: int64

Duplicate rows:
0

In [ ]:
Customer_Demographics_Cleaned_Dataset = "Customer_Demographics_Cleaned_Dataset.csv"

df.to_csv(Customer_Demographics_Cleaned_Dataset, index=False)

print("Save as:", Customer_Demographics_Cleaned_Dataset)

Save as: Customer_Demographics_Cleaned_Dataset.csv

In [ ]:
from google.colab import files

files.download("Customer_Demographics_Cleaned_Dataset.csv")